import { Link } from "react-router-dom";
import {
  ArrowRight,
  Play,
  Radio,
  Ear,
  GraduationCap,
  Eye,
  Mic,
} from "lucide-react";
import Nav from "../components/Nav";
import Code from "../components/Code";
import MascotFigure from "../components/MascotFigure";
import { LINKS } from "../site";

const PSEUDOCODE = `
SET total TO 0
FOR i FROM 1 TO 5
    total <- total + i
END FOR
PRINT total`;

const VOX = `
main {
    consider an integer total which is equal to 0;

    for (integer i <- 1; i is less or equal to 5; i <- i + 1) {
        total <- i added to total;
    }

    print(total);
}`;

const PRINCIPLES = [
  {
    icon: Ear,
    title: "Every symbol has a spoken form",
    body: '"is greater than", "divided by", "which is equal to". If you can say what the program does, you can nearly type it.',
  },
  {
    icon: GraduationCap,
    title: "The symbols still work",
    body: 'Write > or "is greater than", = or "which equals". Learners graduate to conventional syntax one operator at a time, without switching languages.',
  },
  {
    icon: Eye,
    title: "Nothing is hidden",
    body: "The playground shows the instructions every program compiles to. What the machine actually does is one panel away, not a mystery.",
  },
  {
    icon: Mic,
    title: "It talks back",
    body: "Undeclared names, wrong argument counts and type mismatches are reported with a line and column before anything runs.",
  },
];

export default function About() {
  return (
    <div className="neon-backdrop min-h-full">
      <Nav />

      <main className="mx-auto max-w-6xl px-4 sm:px-6">
        {/* The language */}
        <section className="py-16 md:py-24">
          <p className="panel-title">About the language</p>
          <h1 className="mt-3 text-4xl font-bold tracking-tight text-paper sm:text-5xl">
            <span className="text-neon-red-soft glow-red">Vox</span>, from the
            Latin for{" "}
            <span className="text-neon-blue-soft glow-blue">voice</span>.
          </h1>
          <div className="mt-6 grid gap-10 md:grid-cols-[1.2fr_1fr]">
            <div className="space-y-4 text-lg leading-relaxed text-fog">
              <p>
                Vox is a programming language deliberately shaped like English
                speech to close a specific gap: the one between the first way
                most people are taught to think about programs and the first
                language they are handed to write them in.
              </p>
              <p>
                Computer science freshers usually meet programming through{" "}
                <span className="text-paper">pseudocode</span> - plain-language
                steps on paper, written to be read by a person. Then the real
                language arrives and with it a wall of symbols, semicolons and
                error messages that have nothing to do with the idea they were
                trying to express.
              </p>
              <p>
                Vox offers a syntax very close to the same pseudocode students
                are taught, but with one difference:{" "}
                <span className="text-paper">it runs.</span> You keep the shape
                of the sentences you would write on paper and you get actual
                output back. The compiler underneath is a real one - a lexer and
                parser generated by ANTLR, a type-checking pass, an intermediate
                representation and a virtual machine - so nothing about it is a
                toy.
              </p>
            </div>
            <div className="flex flex-col justify-center gap-3">
              <Link to="/playground?example=natural" className="btn-red">
                <Play size={16} />
                Try it in the playground
              </Link>
              <a
                href={LINKS.journal}
                target="_blank"
                rel="noreferrer"
                className="btn-blue"
              >
                How it was built
                <ArrowRight size={16} />
              </a>
            </div>
          </div>
        </section>

        {/* Pseudocode vs Vox */}
        <section className="py-12">
          <h2 className="text-3xl font-bold text-paper">
            Pseudocode that compiles
          </h2>
          <p className="mt-3 max-w-2xl text-fog">
            The textbook version on the left cannot be run. The Vox version on
            the right prints <span className="font-mono text-paper">15</span>.
          </p>
          <div className="mt-8 grid gap-6 md:grid-cols-2">
            <div className="overflow-hidden rounded-lg border border-line-2 bg-panel">
              <div className="flex h-9 items-center border-b border-line px-4">
                <span className="panel-title">pseudocode, as taught</span>
              </div>
              <pre className="px-4 py-4 font-mono text-[13px] leading-relaxed text-fog">
                <code>{PSEUDOCODE.trim()}</code>
              </pre>
            </div>
            <Code source={VOX} title="the same thing in Vox" accent="red" />
          </div>
        </section>

        {/* Principles */}
        <section className="py-12">
          <div className="grid gap-x-10 gap-y-8 md:grid-cols-2">
            {PRINCIPLES.map(({ icon: Icon, title, body }) => (
              <div key={title} className="flex gap-4">
                <div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-md tube-blue text-neon-blue-soft">
                  <Icon size={18} />
                </div>
                <div>
                  <h3 className="font-semibold text-paper">{title}</h3>
                  <p className="mt-1.5 text-sm leading-relaxed text-fog">
                    {body}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* The mascot */}
        {/* <section className="py-16 md:py-24">
          <p className="panel-title">About the mascot</p>
          <h2 className="mt-3 text-4xl font-bold tracking-tight text-paper">
            Meet <span className="text-neon-red-soft glow-red">Vox</span>. Also
            Vox.
          </h2>

          <div className="mt-8 grid items-center gap-10 md:grid-cols-[1fr_1.1fr]">
            <div className="space-y-4 text-lg leading-relaxed text-fog">
              <p>
                The mascot shares the language's name and is drawn as a{" "}
                <span className="text-paper">radio host</span>. To the person
                listening, a radio host is a creature made of voice alone - you
                never see them, you only ever hear them. For a language named
                after the voice, that felt right.
              </p>
              <p>
                There is a second reading hidden in the red strokes. Look at the
                red parts from the <span className="text-paper">bottom up</span>{" "}
                and the mascot spells its own name:
              </p>
              <ul className="space-y-2 font-mono text-base">
                <li className="flex items-baseline gap-4">
                  <span className="w-6 text-2xl font-bold text-neon-red-soft glow-red">
                    V
                  </span>
                  <span className="text-fog">
                    the body - the collar of the suit, drawn as a V
                  </span>
                </li>
                <li className="flex items-baseline gap-4">
                  <span className="w-6 text-2xl font-bold text-neon-red-soft glow-red">
                    O
                  </span>
                  <span className="text-fog">
                    the head - an oval, like a lit neon sign
                  </span>
                </li>
                <li className="flex items-baseline gap-4">
                  <span className="w-6 text-2xl font-bold text-neon-red-soft glow-red">
                    X
                  </span>
                  <span className="text-fog">
                    the eyes - crossed and grinning about it
                  </span>
                </li>
              </ul>
              <p>
                The blue strokes are the host's outfit: a wide smile, a collar
                and a tie. Red carries the name; blue carries the personality.
              </p>
              <p className="flex items-center gap-2 text-sm">
                <Radio size={16} className="text-neon-blue-soft" />
                <span>
                  Yes, the design owes a nod to{" "}
                  <span className="text-paper">Murder Drones</span>.
                </span>
              </p>
            </div>

            <div className="rounded-xl border border-line bg-panel/60 p-4 sm:p-6">
              <MascotFigure />
            </div>
          </div>
        </section> */}

        {/* CTA */}
        <section className="pb-24">
          <div className="flex flex-wrap items-center justify-between gap-6 rounded-xl tube-red bg-panel p-8">
            <div>
              <h2 className="text-2xl font-bold text-paper">
                Write something in your own words.
              </h2>
              <p className="mt-2 text-fog">
                The playground runs entirely in your browser. Nothing to
                install.
              </p>
            </div>
            <Link to="/playground" className="btn-red">
              <Play size={16} />
              Open the playground
            </Link>
          </div>
        </section>
      </main>
    </div>
  );
}
