import { Link } from "react-router-dom";
import {
  ArrowRight,
  ArrowUpRight,
  BookOpen,
  ChevronRight,
  Play,
  Radio,
} from "lucide-react";
import Nav from "../components/Nav";
import GithubIcon from "../components/GithubIcon";
import Code from "../components/Code";
import { EXAMPLES } from "../examples";
import { LINKS } from "../site";

const PSEUDOCODE = `
SET total TO 0
FOR i FROM 1 TO 5
    total <- total + i
END FOR
PRINT total`;

const VOX = `
main {
    consider an integer total which is equal to 0;

    for (integer i <- 1; i is less or equal to 5; i <- i + 1) {
        total <- i added to total;
    }

    print(total);
}`;
const HERO_SNIPPET = `
main {
    consider an integer start which is equal to 13;
    hailstone(start);
}`;

const NATURAL = `
integer hailstone(integer n) {
    while (n is greater than 1) {
        print(n);
        if ((n remainder from 2) is 0) {
            n = n divided by 2;
        } else {
            n = n times 3 added to 1;
        }
    }
    return n;
}`;

const SYMBOLIC = `
integer hailstone(integer n) {
    while (n > 1) {
        print(n);
        if (n % 2 == 0) {
            n = n / 2;
        } else {
            n = n * 3 + 1;
        }
    }
    return n;
}`;

const PIPELINE = [
  { name: "Source", detail: "a .vox file" },
  { name: "Lexer & parser", detail: "generated by ANTLR from one grammar" },
  { name: "Parse tree", detail: "checked for names, types, and arity" },
  { name: "IR", detail: "a flat list of simple instructions" },
  { name: "Virtual machine", detail: "executes the IR, frame by frame" },
];

const FEATURES = [
  {
    title: "Reads like English",
    body: 'Every operator has a spoken form. "is greater than", "divided by", "which is equal to" - and the symbols still work if you prefer them.',
  },
  {
    title: "Checked before it runs",
    body: "Undeclared variables, wrong argument counts, and type mismatches are caught at compile time - and underlined in the editor as you type.",
  },
  {
    title: "Runs entirely here",
    body: "The playground has no backend. The compiler and VM are TypeScript, running in a Web Worker in your browser.",
  },
  {
    title: "Exact integers",
    body: "Integers never overflow. factorial(25) is 15511210043330985984000000, not a wrapped negative number.",
  },
  {
    title: "Two engines, one grammar",
    body: "A Java reference implementation and the TypeScript port share the grammar and pass the same regression suite.",
  },
  {
    title: "Look inside",
    body: "The playground shows the intermediate representation every program compiles to, instruction by instruction.",
  },
];

export default function Landing() {
  return (
    <div className="neon-backdrop min-h-full">
      <Nav />

      <main className="mx-auto max-w-6xl px-4 sm:px-6">
        {/* Hero */}
        <section className="items-center gap-12 py-16 md:grid-cols-2 md:py-24">
          <div className="">
            <img
              src="/vox.png"
              alt="Vox, the mascot"
              className="mb-8 h-36 w-auto drop-shadow-[0_0_18px_rgba(255,43,43,0.5)]"
            />
            <h1 className="text-5xl font-bold tracking-tight text-neon-red-soft glow-red sm:text-6xl">
              Vox
            </h1>
          </div>
          <div className=" grid md:grid-cols-2">
            <div className="w-full">
              <p className="mt-4 text-2xl font-medium text-paper">
                A programming language that reads like English.
              </p>
              <p className="mt-4 max-w-md text-fog">
                Pseudocode that actually runs. Built from scratch with ANTLR,
                compiled to a tiny intermediate representation, and executed by
                a custom virtual machine - right here in your browser.
              </p>
            </div>
            <div>
              <Code source={HERO_SNIPPET} title="hello.vox" />
              <div className="mt-8 flex flex-wrap gap-3">
                <Link to="/playground" className="btn-red">
                  <Play size={16} />
                  Open the playground
                </Link>
                <a
                  href={LINKS.journal}
                  target="_blank"
                  rel="noreferrer"
                  className="btn-ghost"
                >
                  <BookOpen size={16} />
                  Read the story
                </a>
                <a
                  href={LINKS.github}
                  target="_blank"
                  rel="noreferrer"
                  className="btn-ghost"
                >
                  <GithubIcon size={16} />
                  GitHub
                </a>
              </div>
            </div>
          </div>
          <div className="space-y-4 text-lg leading-relaxed text-fog mt-4 md:mt-10">
            <p className="text-justify">
              Vox is a programming language deliberately shaped like English
              speech to close a specific gap: the one between the first way most
              people are taught to think about programs and the first language
              they are handed to write them in.
            </p>
            <p className="text-justify">
              Computer science freshers usually meet programming through{" "}
              <span className="text-paper">pseudocode</span> - plain-language
              steps on paper, written to be read by a person. Then the real
              language arrives, and with it a wall of symbols, semicolons and
              error messages that have nothing to do with the idea they were
              trying to express.
            </p>
            <p className="text-justify">
              Vox offers a syntax very close to the same pseudocode students are
              taught, but with one difference:{" "}
              <span className="text-paper">it runs.</span> You keep the shape of
              the sentences you would write on paper, and you get actual output
              back. The compiler underneath is a real one - a lexer and parser
              generated by ANTLR, a type-checking pass, an intermediate
              representation, and a virtual machine - so nothing about it is a
              toy.
            </p>
          </div>
        </section>
        <section className="py-12">
          <h2 className="text-3xl font-bold text-paper">
            Pseudocode that compiles
          </h2>
          <p className="mt-3 max-w-2xl text-fog">
            The textbook version on the left cannot be run. The Vox version on
            the right prints <span className="font-mono text-paper">15</span>.
          </p>
          <div className="mt-8 grid gap-6 md:grid-cols-2">
            <div className="overflow-hidden rounded-lg border border-line-2 bg-panel">
              <div className="flex h-9 items-center border-b border-line px-4">
                <span className="panel-title">pseudocode, as taught</span>
              </div>
              <pre className="px-4 py-4 font-mono text-[13px] leading-relaxed text-fog">
                <code>{PSEUDOCODE.trim()}</code>
              </pre>
            </div>
            <Code source={VOX} title="the same thing in Vox" accent="red" />
          </div>
        </section>

        {/* Natural vs symbolic */}
        <section className="py-16">
          <h2 className="text-3xl font-bold text-paper">
            Say it, or spell it.
          </h2>
          <p className="mt-3 max-w-2xl text-fog">
            Both of these are valid Vox. They compile to exactly the same
            instructions, so you can mix the two freely - even mid-expression.
          </p>
          <div className="mt-8 grid gap-6 md:grid-cols-2">
            <Code source={NATURAL} title="natural" accent="red" />
            <Code source={SYMBOLIC} title="symbolic" accent="blue" />
          </div>
        </section>

        {/* Pipeline */}
        <section className="py-16">
          <h2 className="text-3xl font-bold text-paper">How a program runs</h2>
          <ol className="mt-8 grid gap-8 md:grid-cols-5">
            {PIPELINE.map((stage, i) => (
              <li key={stage.name} className="relative flex min-w-0">
                <div
                  className={`h-full w-full rounded-lg bg-panel p-4 ${
                    i % 2 === 0 ? "tube-red" : "tube-blue"
                  }`}
                >
                  <div className="text-xs text-fog">step {i + 1}</div>

                  <div
                    className={`mt-1 font-semibold ${
                      i % 2 === 0 ? "text-neon-red-soft" : "text-neon-blue-soft"
                    }`}
                  >
                    {stage.name}
                  </div>

                  <div className="mt-2 text-sm text-fog">{stage.detail}</div>
                </div>

                {i < PIPELINE.length - 1 && (
                  <ChevronRight
                    aria-hidden
                    size={18}
                    className="absolute -right-5 top-1/2 hidden translate-x-1/4 -translate-y-1/2 text-fog md:block"
                  />
                )}
              </li>
            ))}
          </ol>
        </section>

        {/* Features */}
        <section className="py-16">
          <div className="grid gap-x-10 gap-y-8 md:grid-cols-3">
            {FEATURES.map((f) => (
              <div key={f.title}>
                <h3 className="font-semibold text-paper">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-fog">
                  {f.body}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* Examples */}
        <section className="py-16">
          <h2 className="text-3xl font-bold text-paper">Try an example</h2>
          <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {EXAMPLES.map((ex) => (
              <Link
                key={ex.id}
                to={`/playground?example=${ex.id}`}
                className="group rounded-lg border border-line bg-panel p-5 transition-all hover:border-neon-blue hover:shadow-[0_0_14px_rgba(61,123,255,0.35)]"
              >
                <div className="font-semibold text-paper group-hover:text-neon-blue-soft">
                  {ex.name}
                </div>
                <div className="mt-2 text-sm text-fog">{ex.blurb}</div>
                <div className="mt-4 flex items-center gap-1 text-xs text-neon-blue-soft opacity-0 transition-opacity group-hover:opacity-100">
                  open in playground
                  <ArrowUpRight size={13} />
                </div>
              </Link>
            ))}
          </div>
        </section>
      </main>

      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-8 text-sm text-fog sm:px-6">
          <span>Vox - made by Muzammil Noor</span>
          <div className="flex gap-4">
            <a
              href={LINKS.journal}
              target="_blank"
              rel="noreferrer"
              className="hover:text-paper"
            >
              Journal
            </a>
            <a
              href={LINKS.github}
              target="_blank"
              rel="noreferrer"
              className="hover:text-paper"
            >
              Source
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
