name: Build Vox Compiler (Linux)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: native-image

      - name: Build Native Binary
        run: |
          javac VoxCompiler.java
          jar --create --file VoxCompiler.jar *.class
          native-image -jar VoxCompiler.jar vox

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: vox-linux
          path: ./vox
